CREATE TABLE IF NOT EXISTS T_RATES (
    ID SERIAL PRIMARY KEY NOT NULL,
    BRAND_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    PRICE INT NOT NULL,
    CURRENCY_CODE VARCHAR(3) NOT NULL
);